services:
 db:
  image: postgres:latest
  ports:
   - "${POSTGRES_PORT}:5432"
  restart: always
  environment:
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

 adminer:
  image: adminer:latest
  restart: always
  ports:
   - "${ADMINER_PORT}:8080"

 keycloak:
  image: quay.io/keycloak/keycloak:latest
  ports:
   - "${KEYCLOAK_PORT}:8080"
  environment:
   KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
   KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  volumes:
   - keycloak-data:/opt/keycloak/data
  command:
   - start-dev
   - --db=dev-file

volumes:
 keycloak-data:
  driver: local
